version: '3.4'

name: rsww-gr-mhpl

networks:
  rsww-network:
    external:
      name: rsww-network

services:
  rabbitmq-main:
    container_name: rabbitmq-gr-mhpl
    image: rabbitmq:3.12.13-management #later change to non management version
    ports:
      - "5672:5672"
      - "15672:15672"  # management opt
    networks:
      - rsww-network

  HotelsRequestService:
    image: ${DOCKER_REGISTRY-}hotelsrequestservice
    container_name: hotels-query-service-gr-mhpl
    build:
      context: .
      dockerfile: HotelsQueryService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Server=postgres-db;Port=5432;Database=hotels;Username=user;Password=postgres;Pooling=true;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - rsww-network
    depends_on:
    - rabbitmq-main




