version: '3'
services:

  admin-postgres_db:
    container_name: admin-postgres_db
    image: postgres
    ports:
      - "6000:5432"
    #  - "5432:5432"
    environment:
      POSTGRES_PASSWORD: student  
      POSTGRES_USER: postgres
    networks:
      - db-network
        
  rabbitmq-main:
    container_name: rabbitmq-main
    image: rabbitmq:3.12.13-management #later change to non management version
    ports:
      - "5672:5672"
      - "15672:15672"  # management opt     
  rabbitmq-transaction:
    container_name: rabbitmq-transaction
    image: rabbitmq:3.12.13-management #later change to non management version
    ports:
      - "5673:5672"
      - "15673:15672"

  transaction-service:
    image: ricopsych/transaction-service
    environment:
      - spring.rabbitmq.host=rabbitmq-transaction
      - spring.rabbitmq.port=5672
  
  transport-query-service:
    image: ricopsych/rsww-transport-query-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Transports;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default
      
  transport-request-service:
    image: ricopsych/rsww-transport-request-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Transports;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default

  order-service:
    image: ricopsych/rsww-order-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Orders;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default

  catalog-query-service:
    image: ricopsych/rsww-catalog-query-service
    environment:
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
  
  catalog-request-service:
    image: ricopsych/rsww-catalog-request-service
    environment:
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
  
  hotels-request-service:
    image: ricopsych/rsww-hotels-request-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Hotels;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    - rabbitmq-main  
    networks:
      - db-network
      - default
      
  hotels-query-service:
    image: ricopsych/rsww-hotels-query-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Hotels;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    - rabbitmq-main  
    networks:
      - db-network
      - default

  preferences-service:
    image: ricopsych/rsww-preferences-service  
    container_name: preferences-service 
    environment:
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main

  api-gateway:
    image: ricopsych/rsww-gateway
    #build: api-gateway
    container_name: api-gateway
    environment:
      - rabbitConfig__adress=rabbitmq-main
    ports:
      - 8080:80
    depends_on:
      - rabbitmq-main

  frontend:
    image: ricopsych/rsww-frontend
#    build: frontend
    container_name: frontend
    ports:
      - 8032:8080
    #depends_on:
    #  - api-gateway

networks:
  db-network:
    name: admin-postgres_default
#    external: true