version: '3'
services:
#RABBITS
  rabbitmq-main:
    container_name: rabbitmq-main
    image: rabbitmq:3.12.13
  rabbitmq-transaction:
    container_name: rabbitmq-transaction
    image: rabbitmq:3.12.13

  catalog-query-service:
    image: ricopsych/rsww-catalog-query-service
    environment:
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
  
  catalog-request-service:
    image: ricopsych/rsww-catalog-request-service
    environment:
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
  
  transaction-service:
    image: ricopsych/rsww-transaction-service
    environment:
      - spring.rabbitmq.host=rabbitmq-main
      - spring.rabbitmq.port=5672

  transport-query-service:
    image: ricopsych/rsww-transport-query-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Transports;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default

  transport-request-service:
    image: ricopsych/rsww-transport-request-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Transports;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default

  order-service:
    image: ricopsych/rsww-order-service
    environment:
      - postgresConfig__connectionString=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Orders;Username=postgres;Password=student;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
      - rabbitmq-main
    networks:
      - db-network
      - default


  hotels-request-service:
    image: ricopsych/rsww-hotels-request-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Hotels;Username=user;Password=postgres;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    - rabbitmq-main  
    networks:
      - db-network
      - default
      
  hotels-query-service:
    image: ricopsych/rsww-hotels-query-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=admin-postgres_db;Port=5432;Database=RSWW_184387_Hotels;Username=user;Password=postgres;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    - rabbitmq-main  
    networks:
      - db-network
      - default

networks:
  db-network:
    name: admin-postgres_default
    external: true