version: '3'
services:

  # mongo-db:
  #   #build: 
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   #volumes:
     
  postgresql-db:
    container_name: postgresql-db
    #build: 
    image: postgres
    #volumes: ??
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rsww123  
      POSTGRES_USER: admin
      POSTGRES_DB: transport


  rabbitmq-main:
    container_name: rabbitmq-main
    image: rabbitmq:3.12.13-management #later change to non management version
    ports:
      - "5672:5672"
      - "15672:15672"  # management opt
      
  rabbitmq-transaction:
    image: rabbitmq:3.12.13-management #later change to non management version
    ports:
      - "5673:5672"
      - "15673:15672"

  # example-backend-service-1:
  #   build: ./ExampleBackend
  #   environment:
  #     - APP_PORT=8081
  #     - INSTANCE_ID=1
  #   ports:
  #     - 8081:8081

  # example-backend-service-2:
  #   build: ./ExampleBackend
  #   environment:
  #     - APP_PORT=8082
  #     - INSTANCE_ID=2
  #   ports:
  #     - 8082:8082

  # load-balancer-service:
  #   build: ./load-balancer-service
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - example-backend-service-1
  #     - example-backend-service-2

  # transaction-service:
  #   image:
  #   build: 
  #   ports:
 
  #hotel-room-service:
  #build: 
  #image:
  #   ports:

  transport-query-service:
    image: ricopsych/rsww-transport-query-service
    environment:
      - postgresConfig__connectionString=Server=postgresql-db;Port=5432;Database=RSWW_184387_Hotels;Username=admin;Password=rsww123;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    #  - postgresql-db
      - rabbitmq-main
    #ports:
  transport-request-service:
    image: ricopsych/rsww-transport-request-service
    environment:
      - postgresConfig__connectionString=Server=postgresql-db;Port=5432;Database=RSWW_184387_Hotels;Username=admin;Password=rsww123;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    #  - postgresql-db
      - rabbitmq-main

  order-service:
    image: ricopsych/rsww-order-service
    environment:
      - postgresConfig__connectionString=Server=postgresql-db;Port=5432;Database=RSWW_184387_Orders;Username=admin;Password=rsww123;Pooling=true;
      - rabbitConfig__adress=rabbitmq-main
    depends_on:
    #  - postgresql-db
      - rabbitmq-main

  #catalog-read-service:
    #build: 
    #image:
  #   ports:

  #catalog-write-service:
    #build: 
    #image:
  #   ports:

  #frontend:
    #build: 
    #image:
  #   ports:

    



