spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    exchange_name: transactions-exchange
    incoming_transactions_queue: incoming-transactions-queue
    incoming_routing_key: incoming.#
