@startuml
class HotelsQueryHandler {
    + HotelsQueryHandler(logger:Serilog.ILogger, config:IConfiguration, connectionFactory:IConnectionFactory, context:ApiDbContext)
}
ConsumerServiceBase <|-- HotelsQueryHandler
@enduml
